// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from "contentful";

export interface ICaseStudyFields {
  /** Title */
  title: string;

  /** slug */
  slug: string;

  /** Summary */
  summary: string;

  /** Thumbnail */
  thumbnail: Asset;

  /** Duration */
  duration: string;

  /** Tools */
  tools: string;

  /** Role */
  role: string;

  /** Overview */
  overview: string;

  /** Background */
  background?: string | undefined;

  /** Problem */
  problem?: string | undefined;

  /** Solution */
  solution?: string | undefined;

  /** Cover Photo */
  coverPhoto?: Asset | undefined;

  /** Research Summary */
  researchSummary: string;

  /** Design Summary */
  designSummary: string;

  /** Evaluation Summary */
  evaluationSummary?: string | undefined;

  /** Content */
  content: string;
}

export interface ICaseStudy extends Entry<ICaseStudyFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "caseStudy";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export type CONTENT_TYPE = "caseStudy";

export type IEntry = ICaseStudy;

export type LOCALE_CODE = "en-US";

export type CONTENTFUL_DEFAULT_LOCALE_CODE = "en-US";
